name: trans_oadm
model:
  n_tokens: 24
  d_embedding: 8
  d_model: 64
  n_encoder_layers: 1
  aa_kernel_size: 13
  r: 128
  n_side: 3
  s_embedding: 4
  s_model: 64
  n_region: 8
  r_embedding: 4
  r_model: 64
  n_pos_model: 64
  max_len: 152
  sum_d_model: 128   # d_model + s_model
  dual_layers: 2
  att_model: 512
  dim_feedforward: 256
  nhead: 8
  cs_layers: 1       # cross attention layers

train:
  seed: 2023
  max_iter: 1000000
  batch_acc: 2
  valid_step: 2
  batch_size: 16
  num_workers: 1
  clip_norm: 10
  optimizer:
    type: Adam
    lr: 1.e-4
    weight_decay: 0.
    beta1: 0.95
    beta2: 0.999
  scheduler:
    #type: plateau
#    factor: 0.6
#    patience: 10
#    min_lr: 1.e-6
    type: